heat_template_version: 2014-10-16

description: A template to deploy a load balanced web server

parameters:

resources:

  myloadbalancer:
    type: OS::Neutron::LBaaS::LoadBalancer
    properties:
      vip_subnet: "4ba321db-9247-454b-9274-faad8ec76461"
 
  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: 1fa7fade-2722-4677-9e2b-da22d385202b
      port_id: { get_attr: [myloadbalancer, vip_port_id ]}
 
  mylistener:
    type: OS::Neutron::LBaaS::Listener
    properties:
      protocol: HTTP
      protocol_port: 8080
      loadbalancer: {get_resource: myloadbalancer}

  mypool:
    type: OS::Neutron::LBaaS::Pool
    properties:
      lb_algorithm: ROUND_ROBIN
      loadbalancer: {get_resource: myloadbalancer}
      listener: {get_resource: mylistener}
      protocol: HTTP

  server_nodes:
    type: OS::Heat::ResourceGroup
    properties:
      count: 3
      resource_def:
        type: https://raw.githubusercontent.com/mathieugh/test2/746a3974d7b14465fee3aef469dd0dc312df3ba4/server.yaml
        properties: 
          pool: {get_resource: mypool}
  

  mymonitor:
    type: OS::Neutron::LBaaS::HealthMonitor
    properties:
      delay: 15000
      max_retries: 2
      pool: {get_resource: mypool}
      timeout: 5000
      type: HTTP

outputs:
    instance_ip6:
      value: {get_attr: [server_nodes, show]}
      description: Information on the resource group.
